"""
Author: Mohammadamin Barekatain, Ziga Avsec
Affiliation: TUM
Goal: Train and evaluate models for the iDeep experiment
Run: snakemake
"""


import os
DATADIR = '../../../Data/RBP/iDeep/'
RAWDATADIR = DATADIR + '/raw/'

RBPS = [i for i in os.listdir(RAWDATADIR) if not i.startswith('.')]

ideep_features = ['motif_fea.gz',
                  'matrix_RNAkmers.tab.gz',
                  'matrix_RNAfold.tab.gz',
                  'matrix_RegionType.tab.gz',
                  'matrix_Response.tab.gz',
                  'matrix_Cobinding.tab.gz',
                  'sequences.fa.gz']
features_new = ['positions.csv']

features = ideep_features + features_new

data_folds = ["training", "test"]

assert len(RBPS) == 31
assert len(features) == 8

#--------------------------------------------
rule all:
    input:
        # expand(RAWDATADIR + "/{rbp_name}/5000/{df}_sample_0/positions.csv",
        #        rbp_name=RBPS,
        #        df=data_folds),
        DATADIR + "/iDeep_auc.csv",
        DATADIR + "/iDeep_auprc.csv"
#--------------------------------------------

rule add_positions_csv:
    input:
        fa = RAWDATADIR + "/{rbp_name}/5000/{df}_sample_0/sequences.fa.gz"
    output:
        csv = RAWDATADIR + "/{rbp_name}/5000/{df}_sample_0/positions.csv"
    script:
        "nearest_refpoints.R"


rule train:
    input:
        expand(RAWDATADIR + "/{rbp_name}/5000/{df}_sample_0/{fea}", rbp_name=RBPS, fea=features, df=data_folds),
    output:
        expand(DATADIR + "/iDeep_original/{rbp_name}.csv", rbp_name=RBPS),
        expand(DATADIR + "/iDeep_scalar_position_gam/{rbp_name}.csv", rbp_name=RBPS),
        expand(DATADIR + "/iDeep_scalar_position_relu/{rbp_name}.csv", rbp_name=RBPS)
    script:
        "train.py"

rule evaluate:
    input:
        expand(DATADIR + "/iDeep_original/{rbp_name}.csv", rbp_name=RBPS),
        expand(DATADIR + "/iDeep_scalar_position_gam/{rbp_name}.csv", rbp_name=RBPS),
        expand(DATADIR + "/iDeep_scalar_position_relu/{rbp_name}.csv", rbp_name=RBPS)
    output:
        DATADIR + "/iDeep_auc.csv",
        DATADIR + "/iDeep_auprc.csv"
    script:
        "model_evaluation.py"
